config/routes.rb
Rails.application.routes.draw do
  get '/sitemap' => redirect('https://eureka-image.s3.amazonaws.com/chancetochance.world/sitemap.xml.gz')
  get '/sitemap' => redirect('https://eureka-image.s3.amazonaws.com/eureka-campus/sitemap.xml.gz')
  
  devise_for :tourists, controllers: {
    sessions:      'tourists/sessions',
    passwords:     'tourists/passwords',
    registrations: 'tourists/registrations'
  }

  devise_for :guiders, controllers: {
    sessions:      'guiders/sessions',
    passwords:     'guiders/passwords',
    registrations: 'guiders/registrations'
  }

  resources :plans 
  get "/market" => "plans#index"
  root      'plans#top'
  get       'plans/:id/top' => "plans#top"
  post "plans/:id/purchase", to: "plans#purchase"
  get  "plans/:id/purchase" => "plans#purchase"
  get  "plans/:id/fail"     => "plans#fail"
  
  resources :professions
  get '/test' => "professions#category"
  get '/test/list' => "professions#index"
  get '/professions/:id/top' => "professions#top"
  
  get '/category' => 'category#index'

  resources :tests
  get '/blog' => 'tests#index'
  get '/blog/new' => 'tests#new'
  get '/guideline' => 'tests#guideline'
  
  resources :guiders
  get '/post' => "guiders#post"
  post "/guiders/:id/approve" => "guiders#approve_guider", as: "approve_guider"
  get  "/guiders/:id/approve" => "guiders#approve_guider"
  get  "/mypage" => "guiders#top_assistant"
  
  get  '/help' => 'inquiry#index'
  post '/help/confirm' => 'inquiry#confirm'
  post '/help/thanks' => 'inquiry#thanks'
  resources :about, :only => :index
  resources :tos, :only => :index
  resources :compliance, :only => :index
  resources :tokutei, :only => :index

end

app/models/guider.rb
class Guider < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, 
         :recoverable, :rememberable, :trackable, :validatable
         
  mount_uploader :photo, BookUploader
  mount_uploader :driver, DriverUploader

  has_many :plans
  has_many :professions
  has_many :tests
  belongs_to :tourist

  after_create :send_admin_mail
  def send_admin_mail
    AdminMailer.new_guider_waiting_for_approval(self).deliver_now
    AdminMailer.new_guider_confirmation(self).deliver_now
  end

end

app/models/home.rb
class Home < ActiveRecord::Base
	belongs_to :guider
	belongs_to :plan
end

app/models/inquiry.rb
class Inquiry
  include ActiveModel::Model
 
  attr_accessor :name, :email, :message
 
  validates :name, :presence => {:message => '名前を入力してください'}
  validates :email, :presence => {:message => 'メールアドレスを入力してください'}
end

app/models/kakomon.rb
class Kakomon < ActiveRecord::Base
end

app/models/plan.rb
class Plan < ActiveRecord::Base
	belongs_to :guider
	belongs_to :home
	has_many :tests
	
	mount_uploader :image, ImageUploader
	mount_uploader :copy_image, CopyImageUploader
	mount_uploader :third_image, ThirdImageUploader
	mount_uploader :fourth_image, FourthImageUploader
	mount_uploader :five_image, FiveImageUploader
end

app/models/profession.rb
class Profession < ActiveRecord::Base
	belongs_to :guider
	
end

app/models/test.rb
class Test < ActiveRecord::Base
	belongs_to :plan
	belongs_to :guider

	mount_uploader :book, BookUploader
end

app/models/tourist.rb
class Tourist < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

has_many :guiders
has_many :to_messages
has_many :chats, through: :guiders

devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
	def index
		render layout: false
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

    def index
    	render :layout => nil
    end

    def search
    	render :layout => nil
    end

end

app/controllers/tos_controller.rb
class TosController < ApplicationController

    def index
    	render :layout => nil
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
	
end

app/helpers/categorys_helper.rb
module CategorysHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/guiders_helper.rb
module GuidersHelper
end

app/helpers/inquirys_helper.rb
module InquirysHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/professions_helper.rb
module ProfessionsHelper
end

app/helpers/tests_helper.rb
module TestsHelper



end

app/helpers/tourists_helper.rb
module TouristsHelper
end

app/views/layouts/application.html.erb
  <!DOCTYPE html>
<html lang="ja">
  <head>
    <!-- Goodle Adsense -->
    <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <script>
    (adsbygoogle = window.adsbygoogle || []).push({
    google_ad_client: "ca-pub-8830310600171711",
    enable_page_level_ads: true
     });
    </script>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-130237144-1"></script>
    <script>
     window.dataLayer = window.dataLayer || [];
     function gtag(){dataLayer.push(arguments);}
     gtag('js', new Date());

     gtag('config', 'UA-130237144-1');
    </script>
    <title>Eureka | ユリイカ</title>
    <meta name="description" content="">
    <meta name="keywords" content="Eureka, 大学, 資格・体験談, テスト, ユリイカ">
    <meta name="viewpoint" content="width=devise-width,initial-scale=1.0">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags  %>
    <!-- Google Console Search -->
    <meta name="google-site-verification" content="uh4J6YQwgfL0Q9XnjCyjTV2xB16q7eXGFCHfdq2UNLQ" />
    
  </head>  

  <body class="photo">
    <header>
     <div>
      <div class="head-container">
       <nav class="headed">
        <li class="left">
         <div class="fine">

          <div class="full_max">
           <div class="full">
            <h1 class="eureka"><a style="color: #E47911;" href="/plans/:id/top">Eureka</a></h1>
            <%= form_tag plans_path, :method => 'get', :class => 'gopro' do %>
                   <div class="question_answer"><%= text_field_tag :search, params[:search], class: "fun_interview", placeholder: '' %></div>
                   <div class="interview_answer"><%= submit_tag "", :name => nil, class: "interview" %></div>
             <% end %>
             
           </div>
           

          </div>
         <div>

        </li>
       
        <% if guider_signed_in? %>
          <div class="guider_nav">
            <span style="top: 18px; margin-top: 0px;"><%= current_guider.nickname %>
              <ul>
                  <li class="category">
                    <a class="guider-category", href="/guiders/<%= current_guider.id%>/edit ">マイページ</a>
                    <a class="guider-category", href="/guiders/<%= current_guider.id %>/go">プロブレム</a>
                    <%= link_to "ログアウト", destroy_guider_session_path, method: :delete, class: 'guider-category' %>
                  </li>
              </ul>
            </span>
            <a class="plan" href="/guiders/:id/post">投稿</a>
          </div>
          
        <% end %>

        <% if tourist_signed_in? %>
             <li class="first">
                <%= link_to "Logout", destroy_tourist_session_path, method: :delete, class: 'logout' %>
              </li>
              <li class="second">
                <a class='post' href="/tourists/show">Contact</a>
              </li>
         
        <% end %>

        <% if ! (guider_signed_in? or tourist_signed_in?) %>
         
             
             <li class="first"><%= link_to "新規登録", new_guider_registration_path, class: 'post' %></li>
             <li class="second"><%= link_to "ログイン", new_guider_session_path, class: 'post' %></li>
             
          
        <% end %>

        <div class="sp">
          <% if ! (guider_signed_in? or tourist_signed_in?) %>
           <div class="grid-6">
            <div class="user_nav grid-6">
              <span class="samurai" style=" 
                width: 300px;
                height: 0px;
                bottom: 5px;
                margin-bottom: 0px;
                padding-bottom: 0px;
                padding-top: 0px;
                margin-left: 0px;
                padding-right: 11px;">
                <ul class="user__info">
                 <li>
                  <%= link_to "traveller", new_tourist_session_path, class: 'post' %>
                  <%= link_to "guider", new_guider_session_path, class: 'post' %>
                 </li>
                </ul>
              </span>
            </div>
           </div>
          <% end %>
        </div>
       

       </nav>
        <div class="all-star" style="margin-bottom: 10px;">
         
          <i style="margin-left: 126px;" class="fas fa-bars"></i>
          <a class="category-id" href="/categorys">カテゴリー<br /></a>
          <i class="fas fa-book" style="margin-left: 15px;"></i>
          <a class="category-id" href="/plans" >教科書</a>
          <i class="fas fa-file-alt" style="margin-left: 15px;"></i>
          <a class="category-id" href="/tests">スキルアップ</a>
          <i class="fas fa-file-alt" style="margin-left: 15px;"></i>
          <a class="category-id" href="/professions/:id/category">テスト対策</a>
        
        </div>

       <div class="mbar">
      </div>
     </div>
    </header>

    <%= yield %>
    
    <footer class="shita">
      
      <div class="category-footer">
        
           <div class="category-footer2">
            <div style="display: block;">
               <h3 class="footer-word">Eurekaについて</h3>
               <a class="footer-word1" href="/plans/:id/eureka">Eurekaについて</a>
              
            </div>
           </div>
           <div class="category-footer2">
            <div style="display: block;">
               <h3 class="footer-word">ヘルプ＆ガイド</h3>
               <a class="footer-word1" href="/plans/:id/inquirys">ヘルプ</a>
            </div>
           </div>
           <div class="category-footer2">
            <div style="display: block;">
               <h3 class="footer-word">プライバシーと利用規約</h3>
               <a class="footer-word1"  href="">プライバシーポリシー</a>
               <a class="footer-word1"  href="/guiders/:id/accepted">ユリイカ利用規約</a>
               <a class="footer-word1"  href="">コンプライアンスポリシー</a>
               <a class="footer-word1"  href="">特定商取引に関する表記</a>
               
            </div>
           </div>
           <div class="category-footer2">
            <div style="display: block;">
              <h3 style="text-align: center;" class="footer-word">国</h3>
              <a class="footer-word1" style="margin-left: 10px; text-align: center;" href="">日本</a>
            </div>
           </div>
        

      </div>

      <div class="shita1">
        <p style="font-size: 14px; color: inherit; text-align: center;">
         © 2018 Eureka
        </p>
      </div>
      
  </body>
</html>